import { Alert, Box, Button, CircularProgress, Snackbar, Stack, Typography } from '@mui/material';
import AddIcon from '@mui/icons-material/Add';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import type { User } from '../../types/auth';
import { userApi } from './userApi';
import { UserDialog } from './UserDialog';
import { UserTable } from './UserTable';
import type { UserValues } from './userSchema';
function message(error: unknown) { return error instanceof Error ? error.message : 'The operation could not be completed.'; }
export function UsersPage() { const client = useQueryClient(); const [editing, setEditing] = useState<User | undefined>(); const [dialogOpen, setDialogOpen] = useState(false); const [notice, setNotice] = useState<string>(); const users = useQuery({ queryKey: ['users'], queryFn: userApi.list }); const roles = useQuery({ queryKey: ['roles'], queryFn: userApi.roles }); const invalidate = () => client.invalidateQueries({ queryKey: ['users'] }); const save = useMutation({ mutationFn: (values: UserValues) => editing ? userApi.update(editing.id, values) : userApi.create({ ...values, password: values.password ?? '' }), onSuccess: () => { invalidate(); setDialogOpen(false); setEditing(undefined); setNotice('User saved successfully.'); } }); const toggle = useMutation({ mutationFn: (user: User) => user.active ? userApi.deactivate(user.id) : userApi.activate(user.id), onSuccess: () => { invalidate(); setNotice('User status updated successfully.'); } }); if (users.isError || roles.isError) return <Alert severity="error">Unable to load user management data. {message(users.error ?? roles.error)}</Alert>; return <Box><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" alignItems={{ sm: 'center' }} spacing={2} sx={{ mb: 3 }}><div><Typography variant="h4" component="h1">Users</Typography><Typography color="text.secondary">Create, update, and manage access to TransitOps.</Typography></div><Button startIcon={<AddIcon/>} variant="contained" onClick={() => { setEditing(undefined); setDialogOpen(true); }}>Create user</Button></Stack>{roles.isLoading ? <CircularProgress aria-label="Loading roles"/> : <UserTable users={users.data ?? []} loading={users.isLoading} onEdit={(user) => { setEditing(user); setDialogOpen(true); }} onToggle={toggle.mutate}/>}<UserDialog open={dialogOpen} user={editing} roles={roles.data ?? []} pending={save.isPending} error={save.isError ? message(save.error) : undefined} onClose={() => setDialogOpen(false)} onSubmit={save.mutate}/><Snackbar open={!!notice} autoHideDuration={4000} onClose={() => setNotice(undefined)} message={notice}/></Box>; }
